/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechtlichesSlugRouteImport } from './routes/rechtliches/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesSlugRoute = RechtlichesSlugRouteImport.update({
  id: '/rechtliches/$slug',
  path: '/rechtliches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rechtliches/$slug': typeof RechtlichesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rechtliches/$slug': typeof RechtlichesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rechtliches/$slug': typeof RechtlichesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rechtliches/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rechtliches/$slug'
  id: '__root__' | '/' | '/rechtliches/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RechtlichesSlugRoute: typeof RechtlichesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches/$slug': {
      id: '/rechtliches/$slug'
      path: '/rechtliches/$slug'
      fullPath: '/rechtliches/$slug'
      preLoaderRoute: typeof RechtlichesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RechtlichesSlugRoute: RechtlichesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
